// pages/contact/index.tsx
/*
 * Copyright (C) 2020 Sandip Vaghela
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React from "react"
import Layout from "components/Layout"
import SEO from "components/SEO"

export default PageContactUs

function PageContactUs() {
    return (
        <>
            <SEO
                title="Contact AfterROOT"
                description="view way to contact to AfterROOT"
            />
            <Layout title="Contact Us">
                <main className="main">
                    <div className="m-3 w-auto flex flex-col flex-auto">
                        <h2 className="text-lg">Request for deletation of account and data:</h2>
                        <p className="mt-1">To request for delete your account and data please send email by clicking below button.</p>
                        <p className="mt-1">Please include your name, email address and the app for which you are requesting to delete data in the email.</p>
                        <button className="mt-1 px-2 py-1 border rounded content-center">
                            <a href="mailto:afterhasroot@gmail.com">EMAIL US</a>
                        </button>
                    </div>
                </main>
            </Layout>
        </>
    )
}

// afterroot/src/routes/contact/+page.svelte
<script lang="ts">
  import SEO from "$lib/components/SEO.svelte"
  import { Badge } from "$lib/components/ui/badge"
  import { Button } from "$lib/components/ui/button"
  import * as Card from "$lib/components/ui/card"
  import { ArrowLeft, Mail } from "@lucide/svelte"
</script>

<SEO
  title="Contact Us"
  description="Get in touch with AfterROOT"
/>

<div class="container mx-auto max-w-3xl px-4 py-8">
  <div class="mb-6">
    <Button variant="ghost" size="sm" href="/" class="gap-1 text-muted-foreground hover:text-foreground">
      <ArrowLeft class="size-4" data-icon="inline-start" />
      Back to Home
    </Button>
  </div>

  <Card.Root class="border-border/60">
    <Card.Header>
      <div class="flex items-center gap-2 mb-1">
        <Badge variant="secondary">Contact</Badge>
      </div>
      <Card.Title class="text-3xl font-light">Contact AfterROOT</Card.Title>
      <Card.Description>We're here to help and answer any questions.</Card.Description>
    </Card.Header>

    <Card.Content class="space-y-6">
      <div class="rounded-lg border bg-muted/20 p-5 space-y-3">
        <h2 class="text-base font-medium text-foreground">
          Request for deletion of account and data:
        </h2>
        <p class="text-sm text-muted-foreground leading-relaxed">
          To request deletion of your account and associated data, please send us an email.
        </p>
        <p class="text-sm text-muted-foreground leading-relaxed">
          Please include your name, email address, and the specific app for which you are requesting data deletion.
        </p>
        <div class="pt-2">
          <Button href="mailto:afterhasroot@gmail.com" class="gap-2">
            <Mail class="size-4" data-icon="inline-start" />
            Email Us (afterhasroot@gmail.com)
          </Button>
        </div>
      </div>
    </Card.Content>
  </Card.Root>
</div>
