// afterroot/src/lib/components/Footer.svelte
<script lang="ts">
  import { Separator } from "$lib/components/ui/separator"
  import { siteConfig } from "$lib/config/site"
  import {
    SiFacebook,
    SiGithub,
    SiInstagram,
    SiX,
    SiYoutube,
  } from "@icons-pack/svelte-simple-icons"
</script>

<footer class="w-full mt-auto py-10 bg-background text-foreground/80">
  <div class="container mx-auto px-4 max-w-5xl flex flex-col items-center gap-6">
    <Separator class="w-full opacity-30" />

    <!-- Navigation links -->
    <div class="flex flex-wrap items-center justify-center gap-2 text-sm">
      {#each siteConfig.footerLinks as link, index (link.title)}
        {#if index > 0}
          <span class="text-muted-foreground select-none">•</span>
        {/if}
        <a
          href={link.url}
          target={link.isExternal ? "_blank" : undefined}
          rel={link.isExternal ? "noopener noreferrer" : undefined}
          class="px-2 py-1 text-muted-foreground hover:text-foreground transition-colors rounded-md"
        >
          {link.title}
        </a>
      {/each}
    </div>

    <!-- Social brand links using simple-icons -->
    <div class="flex items-center justify-center gap-4">
      <a
        href={siteConfig.links.igUrl}
        target="_blank"
        rel="noopener noreferrer external"
        aria-label="Find AfterROOT on Instagram"
        class="text-muted-foreground hover:text-foreground transition-colors p-2 rounded-full hover:bg-muted"
      >
        <SiInstagram class="size-4" />
      </a>
      <a
        href={siteConfig.links.ytUrl}
        target="_blank"
        rel="noopener noreferrer external"
        aria-label="Find AfterROOT on YouTube"
        class="text-muted-foreground hover:text-foreground transition-colors p-2 rounded-full hover:bg-muted"
      >
        <SiYoutube class="size-4" />
      </a>
      <a
        href={siteConfig.links.fbUrl}
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Find AfterROOT on Facebook"
        class="text-muted-foreground hover:text-foreground transition-colors p-2 rounded-full hover:bg-muted"
      >
        <SiFacebook class="size-4" />
      </a>
      <a
        href={siteConfig.links.twitterUrl}
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Find AfterROOT on X / Twitter"
        class="text-muted-foreground hover:text-foreground transition-colors p-2 rounded-full hover:bg-muted"
      >
        <SiX class="size-4" />
      </a>
      <a
        href={siteConfig.links.githubUrl}
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Projects on GitHub"
        class="text-muted-foreground hover:text-foreground transition-colors p-2 rounded-full hover:bg-muted"
      >
        <SiGithub class="size-4" />
      </a>
    </div>

    <!-- Copyright and details -->
    <div class="text-center text-xs text-muted-foreground leading-relaxed">
      <p>
        {siteConfig.copyright} • v{siteConfig.version}
        {#if siteConfig.commitSha}
          -
          <a
            href={`${siteConfig.links.githubProjectUrl}/tree/${siteConfig.commitShaLong}`}
            target="_blank"
            rel="noopener noreferrer"
            class="underline hover:text-foreground"
          >
            {siteConfig.commitSha}
          </a>
        {/if}
        • Built on {siteConfig.buildDate}
      </p>
      <p class="mt-1">
        Developed with
        <a
          href={siteConfig.links.jetbrains}
          target="_blank"
          rel="noopener noreferrer"
          class="underline hover:text-foreground"
        >
          IntelliJ IDEA
        </a>
        and
        <a
          href={siteConfig.links.vsCode}
          target="_blank"
          rel="noopener noreferrer"
          class="underline hover:text-foreground"
        >
          VS Code
        </a>
      </p>
    </div>
  </div>
</footer>

// src/components/Footer/index.tsx
/*
 * Copyright (C) 2020-2022 Sandip Vaghela
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { Component } from "react"
import config from "../../../data/SiteConfig"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import {
  faFacebook,
  faGithub,
  faInstagram,
  faTwitter,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons"

interface IProps {}

interface IState {
  extraLinks: { title: string; url: string; isExternal: boolean }[]
}

class Footer extends Component<IProps, IState> {
  private COMMIT: any

  constructor(props: IProps) {
    super(props)
    this.state = {
      extraLinks: [],
    }
  }

  componentDidMount() {
    this.setState({
      extraLinks: config.footerLinks,
    })
  }

  render() {
    return (
      <footer>
        <div className="mx-4 border-t border-slate-300/10" />
        <div className="flex flex-wrap flex-row items-center justify-center p-2 w-full">
          {this.state.extraLinks.map((link) => {
            let separator, target
            if (
              this.state.extraLinks.indexOf(link) !=
              this.state.extraLinks.length - 1
            ) {
              separator = "|"
            }
            if (link.isExternal) {
              target = "_blank"
            }
            return (
              <span key={link.title}>
                <a className="px-2" href={link.url} target={target}>
                  {link.title}
                </a>
                {separator}
              </span>
            )
          })}
        </div>
        <ul className="flex flex-wrap justify-center items-center">
          <li className="mx-2">
            <a
              className="text-white/50 hover:text-white transition-colors"
              href={config.links.igUrl}
              rel="noopener noreferrer"
              aria-label="Find AfterROOT on Instagram"
              target="_blank"
              title="Find AfterROOT on Instagram"
            >
              <FontAwesomeIcon icon={faInstagram} />
            </a>
          </li>
          <li className="mx-2">
            <a
              className="text-white/50 hover:text-white transition-colors"
              href={config.links.ytUrl}
              rel="noopener noreferrer"
              aria-label="Find AfterROOT on YouTube"
              target="_blank"
              title="Find AfterROOT on YouTube"
            >
              <FontAwesomeIcon icon={faYoutube} />
            </a>
          </li>
          <li className="mx-2">
            <a
              className="text-white/50 hover:text-white transition-colors"
              href={config.links.fbUrl}
              rel="noopener noreferrer"
              aria-label="Find AfterROOT on Facebook"
              target="_blank"
              title="Find AfterROOT on Facebook"
            >
              <FontAwesomeIcon icon={faFacebook} />
            </a>
          </li>
          <li className="mx-2">
            <a
              className="text-white/50 hover:text-white transition-colors"
              href={config.links.twitterUrl}
              rel="noopener noreferrer"
              aria-label="Find AfterROOT on Twitter"
              target="_blank"
              title="Find AfterROOT on Twitter"
            >
              <FontAwesomeIcon icon={faTwitter} />
            </a>
          </li>
          <li className="mx-2">
            <a
              className="text-white/50 hover:text-white transition-colors"
              href={config.links.githubUrl}
              rel="noopener noreferrer"
              aria-label="Projects on GitHub"
              target="_blank"
              title="Projects on GitHub"
            >
              <FontAwesomeIcon icon={faGithub} />
            </a>
          </li>
        </ul>
        <div className="flex flex-wrap flex-row items-center justify-center p-2 w-full">
          <span className="text-center text-xs" id="_version">
            {config.copyright} • v{config.version}-
            {
              <a
                className="underline"
                target="_blank"
                rel="noreferrer"
                href={`${config.links.githubProjectUrl}/tree/${config.commitShaLong}`}
              >
                {config.commitSha}
              </a>
            }{" "}
            • Built on {config.buildDate}
            <br />
            Developed with{" "}
            {
              <a className="underline" href={config.links.jetbrains}>
                IntelliJ IDEA
              </a>
            }{" "}
            and{" "}
            {
              <a className="underline" href={config.links.vsCode}>
                VS Code
              </a>
            }
          </span>
        </div>
      </footer>
    )
  }
}

export default Footer
